baseurl = "https://username.github.io/" # Here you can put whatever custom domain you want.
title = "Ken Adams"
copyright = "&copy; 2019 Regina Phalange"
theme = "academic"

enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10
disqusShortname = ""
googleAnalytics = ""
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false
enableGitInfo = false

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).

[params]
  color_theme = "rudhtheme"
  font = "rudhfont"

  # Your details.
  name = "Ken Adams"
  role = "Profession"
  organizations = [ { name = "Institute Name", url = "https://en.wikipedia.org/wiki/Friends" } ]

  gravatar = false  # Get your avatar from Gravatar.com? (true/false)
  avatar = "profile/portrait.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.
  # email = "example@example.org"
  email1 = "rudhkul" # using cryptedmail
  email2 = "gmail" # using cryptedmail
  email3 = "com" # using cryptedmail
  address = "You put your address here"
  office_hours = "Morning to Night"
  phone = "888 888 888"
  skype = ""
  # telegram = ""

  # Diplay a logo in navigation bar rather than title (optional).
  #   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
  logo = ""

  # To use Google Maps, set `map = 1` and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # Map provider:
  #   0: No map
  #   1: Google Maps
  map = 0
  map_api_key = ""
  latitude = "33.9745"
  longitude = "-117.3254"
  zoom = 17

  date_format = "Jan 2, 2006"
  time_format = "3:04 PM"

  reading_time = true
  comment_count = true
  section_pager = false
  math = false
  highlight = true
  highlight_languages = []
  sharing = true
  privacy_pack = false

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = ['rudh2019layout.css', 'cryptedmail.css', 'rudh2018.css', 'rudhaboutme.css', 'rudhnav.css', 'slick.css', 'slick-theme.css', 'rudhslick.css']
  custom_js  = ['jquery-2.2.0.min.js', 'slick.js', 'rudhslick.js']

  # FOOTER PARAMETERS
  footmark = ""
  stacklogo = "logo/logo.png"
  legalblurb = "Whatever I write here comes from my own knowledge/opinion. It does not belong to anyone else, but me."

  # HEADER PARAMETERS
  watermark = "background/continuity.png"


  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

[[params.social]]

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = 'mailto:rudhkul@gmail.com'  # For a direct email link, use "mailto:rudhkul@gmail.com"
    cv = true

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.co.in/"
    cv = true

  [[params.social]]
    icon = "researchgate"
    icon_pack = "ai"
    link = "https://www.researchgate.net/"
    cv = true

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/rudhkul"
    cv = true

  [[params.social]]
    icon = "publons"
    icon_pack = "ai"
    link = "//publons.com/"
    cv = true

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com"
    cv = false

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//www.linkedin.com/"
    cv = false

  [[params.social]]
    icon = "skype"
    icon_pack = "fa"
    link = ""
    cv = false

  [[params.social]]
    icon = "cv"
    icon_pack = "ai"
    link = "/files/academic_cv.pdf" # If you like this CV, its source files are available on my github account.
    cv = true



# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
[params.menus]
  # Align the main menu to the right of the page? (true/false)
  align_right = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "CV"
  url = "#CV"
  weight = 2

[[menu.main]]
  name = "Publications"
  url = "#publication"
  weight = 3

[[menu.main]]
  name = "Research"
  url = "#research"
  weight = 4

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 5

[[menu.main]]
  name = "Blog"
  url = "posts"
  weight = 6

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 7

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"



# Configure the English version of the website.
[Languages.en]
  languageCode = "en-us"

# Configuration of publication pages.
[publications]
  # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "January 2006"

  # Citation style ("apa" or "mla")
  citation_style = "mla"

# Configuration of project pages.
[projects]
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view = 2
  publication_view = 4
  talk_view = 2
